version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=Server=db;Database=AppointmentsDb;User=sa;Password=Test@82$#;
    depends_on:
      - mssql_db
    volumes:
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys

  mssql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: "Test@82$#"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql
volumes:
  sql_data:
